name: app_design_scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - flask==3.0.0
    - requests==2.31.0
    - beautifulsoup4==4.12.2
    - lxml==4.9.3
    - cssutils==2.7.1
    - pillow==10.1.0
    - webcolors==1.13

